[package]
name = "rgit"
version = "0.1.0"
authors = ["icew4ll <icew4ll.io>"]

[dependencies]
subprocess = "0.1.12"
colored = "1.6.0"
csv = "1.0.0-beta.5"
quicli = "0.2.0"
structopt = "0.2.8"
reqwest = "0.8.5"
serde = "1.0.55"
dialoguer = "0.1.0"
console = "0.6.1"
